### ISSUE TITLE
Downloader not working with EBI/SRA accession

### ISSUE THREAD

**Issue by justinshaffer** [Deeeeen/EBI_SRA_Downloader#1]
Hello,

I'm experiencing issues using the tool to download the data here:
https://www.ebi.ac.uk/ena/browser/view/PRJEB29403?show=reads

Here is what I ran:
`python3 EBI_SRA_Downloader.py -ebi PRJEB29403 -all-platform true -all-seqs true
`
Error:
Exception: PRJEB29403 is not a valid EBI study ID

Also tried the SRA accession:
`python3 EBI_SRA_Downloader.py -sra PRJEB29403 -all-platform true -all-seqs true
`

Error:
Exception: PRJEB29403 has no sample or run that is from Illumina

Thanks in advance for any insight.

**Comment by Deeeeen** [comment]
Hi Justin,

It looks like ENA changed their API a bit. This 3yrs old script doesn't support the new changes, but I modified it a bit. Hope it works now. Please feel free to let me know if you have any other questions.

Cheers!

**Comment by justinshaffer** [comment]
Thank you!

I tried to run:
`python3 EBI_SRA_Downloader.py -ebi PRJEB29403 -all-platform true -all-seqs true
`

But received this error:
```
Traceback (most recent call last):
  File "/home/jpshaffer/code/EBI_SRA_Downloader.py", line 783, in <module>
    ebi_create_info_file(study_file_name, args.ebiaccession)
  File "/home/jpshaffer/code/EBI_SRA_Downloader.py", line 257, in ebi_create_info_file
    if is_study.find('IDENTIFIERS').find('SECONDARY_ID') is None:
AttributeError: 'NoneType' object has no attribute 'find'
```

The data are from an Illumina instrument.

Thanks in advance,
